version: '3.8'

services:

  bot:
    image: "${BOT_NAME}-tg_bot-image"
    container_name: "${BOT_NAME}-tg_bot-container"
    stop_signal: SIGINT
    build:
      context: .
    working_dir: "/usr/src/app/${BOT_NAME}-tg_bot"
    volumes:
      - .:/usr/src/app/${BOT_NAME}-tg_bot
    command: sh -c "sleep 10 && python bot.py"
    restart: always
    depends_on:
      - db
    env_file:
      - ".env"
    networks:
      - tg_bot

  db:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=$DB_NAME
      - MONGO_INITDB_ROOT_USERNAME=$DB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$DB_PASS
    restart: always
    ports:
      - "27777:27017"
    networks:
      - tg_bot
    env_file:
      - ".env"
    volumes:
      - ./data:/data/db


networks:
  tg_bot:
    driver: bridge
