version: '3.8'

services:

  bot:
    image: "${BOT_NAME}-tg_bot-image"
    container_name: "${BOT_NAME}-tg_bot-container"
    stop_signal: SIGINT
    build:
      context: .
    working_dir: "/usr/src/app/${BOT_NAME}-tg_bot"
    volumes:
      - .:/usr/src/app/${BOT_NAME}-tg_bot
    command: sh -c "python3 --version && python3 bot.py"
    restart: always
    depends_on:
      - db
      - chrome
    env_file:
      - ".env"
    networks:
      - tg_bot

  db:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=$DB_NAME
      - MONGO_INITDB_ROOT_USERNAME=$DB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$DB_PASS
    restart: always
    ports:
      - "27777:27017"
    networks:
      - tg_bot
    env_file:
      - ".env"
    volumes:
      - ./data:/data/db


  chrome:
    image: selenium/node-chrome:4.21.0
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - tg_bot

  selenium-hub:
    image: selenium/hub:4.21.0
    container_name: selenium-hub
    #    ports:
    #        - "4444:4444"
    networks:
      - tg_bot

networks:
  tg_bot:
    driver: bridge
